#
# Docker compose file for TANGO database, database device server and tango test ds
# the containers are based on images on gerhardlr docker repository (to be moved later)
# the composition provides an external network named [rootdir]_tango_network
# use this network (external:true) if you want your own device servers (in containers) to connect to the network
#
version: '2'
volumes:
  tangodb: {}
        
services:
  tangodb:
    image: gerhardlr/tangodb:latest
    container_name: tangodb    
    hostname: tangodb  
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
    volumes:
      - tangodb:/var/lib/mysql
    networks:
      - tango_network

  databaseds:
    image: gerhardlr/tango_base:latest
    container_name: databaseds
    hostname: databaseds
    depends_on:
      - tangodb
    networks:
      - tango_network
    environment:
      - MYSQL_HOST=tangodb:3306 
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - TANGO_HOST=databaseds:10000 
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - tangodb:3306
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/DataBaseds
      - "2"
      - -ORBendPoint
      - giop:tcp::10000
  tangotestds:
    networks:
      - tango_network
    image: gerhardlr/tango_base:latest
    container_name: tangotestds
    hostname: tangotestds
    depends_on:
      - databaseds
    environment:
      - MYSQL_HOST=tangodb:3306 
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - TANGO_HOST=databaseds:10000 
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - databaseds:10000
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/TangoTest
      - "test"
networks:
  tango_network:
    driver: bridge