#
# Docker compose file that launches an basic ubuntu fce server with vnc access over vnc client and web brower
# the server will run jive at startup
# connect to browser via localhost:6901/?password=vncpassword
#
# Defines:
#   - itango: iTango interactive session
#
# Requires:
#   - tbase/docker compose up
#   - nexternal network is defined by tbase

version: '2'

services:
  tango_dev_testing:
    build: .
    container_name: tango_dev_testing
    environment:
      - TANGO_HOST=databaseds:10000
      - FLASK_APP=App
      - FLASK_ENV=development
    networks:
      - tangoappframework_tango_network
      - local_testing
    stdin_open: true
    tty: true
    volumes:
      - $DEV_HOME:/home/appModule
    expose:
      - "5002"
    ports:
      - "127.0.0.1:5002:5000"
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - databaseds:10000
      - --timeout=30
      - --strict
      - --
#      - bash -it "python"
      - tail -f /dev/null
#      - flask
#      - run
#      - --host=0.0.0.0
networks:
  tangoappframework_tango_network:
    external: true
  local_testing:
    driver: bridge