#
# Docker compose file that launches a container to host a single tango device/client being developed
#
# Requires: 
#   - tbase/docker compose up (containing external service databaseds)
#   - external network is defined by tbase
#
version: '2'

services:
  tango_dev:
    build:      
      context: ../App/xxx_DS/Build
      dockerfile: Dockerfile
    container_name: dev_tango 
    environment:
      - TANGO_HOST=databaseds:10000 
      - FLASK_APP=/app/xxx_DS/app.py
      - FLASK_ENV=development
    networks:
      - tbase_tango_network
      - app_network
    volumes:
      - $HOMEDEV:/app
    expose:
      - "5000"
    ports:
      - "127.0.0.1:5001:5000"
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - databaseds:10000
      - --timeout=30
      - --strict
      - --
     # - tail -f /dev/null
      - flask
      - run
      - --host=0.0.0.0
     # - python
     # - /app/xxx_DS/app.py
networks:
  tbase_tango_network:
    external: true
  app_network:
    driver: bridge 
